"use client";

import { useState } from "react";
import { PaperScript, SceneType } from "@/types/script";

const TYPE_COLOR: Record<SceneType, string> = {
  intro:          "#a78bfa",
  prerequisite:   "#60a5fa",
  hook:           "#fb923c",
  example:        "#38bdf8",
  concept:        "#c084fc",
  analogy:        "#4ade80",
  worked_example: "#a3e635",
  finding:        "#34d399",
  connection:     "#fbbf24",
  summary:        "#e879f9",
};

const TYPE_LABEL: Record<SceneType, string> = {
  intro: "Intro", prerequisite: "Foundations", hook: "Hook",
  example: "Example", concept: "Concept", analogy: "Analogy",
  worked_example: "Worked Example", finding: "Finding",
  connection: "Connection", summary: "Summary",
};

function formatTime(seconds: number) {
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

function buildInVideoScript(script: PaperScript): string {
  const lines: string[] = [
    `SCRIPT: ${script.title.toUpperCase()}`,
    ``,
    script.summary,
    ``,
    `${"─".repeat(60)}`,
    ``,
  ];

  script.scenes.forEach((scene, i) => {
    lines.push(`SCENE ${i + 1} — ${TYPE_LABEL[scene.type].toUpperCase()}`);
    lines.push(`Headline: ${scene.headline}`);
    lines.push(`Duration: ~${formatTime(scene.duration_seconds)}`);
    if (scene.image_prompt) lines.push(`[VISUAL PROMPT: ${scene.image_prompt}]`);
    lines.push(``);
    lines.push(scene.narration);
    lines.push(``);
    if (scene.key_terms && scene.key_terms.length > 0) {
      lines.push(`Key terms: ${scene.key_terms.join(", ")}`);
    }
    lines.push(`${"─".repeat(60)}`);
    lines.push(``);
  });

  const totalSecs = script.scenes.reduce((a, s) => a + s.duration_seconds, 0);
  lines.push(`Total estimated duration: ${formatTime(totalSecs)}`);
  lines.push(`Generated by PaperLens`);
  return lines.join("\n");
}

export default function ScriptExport({ script }: { script: PaperScript }) {
  const [copied, setCopied] = useState(false);
  const [expandedScene, setExpandedScene] = useState<number | null>(null);

  const totalSecs = script.scenes.reduce((a, s) => a + s.duration_seconds, 0);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildInVideoScript(script));
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    const blob = new Blob([buildInVideoScript(script)], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${script.title.slice(0, 40).replace(/[^a-z0-9]/gi, "_")}_script.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full flex flex-col gap-6">
      {/* Title + meta */}
      <div>
        <h2 className="text-2xl font-bold text-white leading-tight">{script.title}</h2>
        <p className="mt-2 text-gray-400 text-sm leading-relaxed">{script.summary}</p>
        <div className="flex gap-4 mt-3 text-xs text-gray-500">
          <span>{script.scenes.length} scenes</span>
          <span>·</span>
          <span>~{formatTime(totalSecs)} total</span>
        </div>
      </div>

      {/* InVideo instructions */}
      <div className="rounded-xl border border-violet-500/30 bg-violet-500/5 px-5 py-4">
        <p className="text-violet-300 font-semibold text-sm mb-1">How to use with InVideo.ai</p>
        <ol className="text-gray-400 text-xs space-y-1 list-decimal list-inside">
          <li>Copy the script below</li>
          <li>Go to <span className="text-violet-400">invideo.ai</span> → Create → AI Script to Video</li>
          <li>Paste the script — InVideo reads the visual prompts in brackets</li>
          <li>Choose a template, pick your AI voiceover, and generate</li>
        </ol>
      </div>

      {/* Action buttons */}
      <div className="flex gap-3">
        <button
          onClick={handleCopy}
          className="flex-1 py-3 rounded-xl font-semibold text-sm bg-gradient-to-r from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500 transition-all text-white"
        >
          {copied ? "Copied!" : "Copy script for InVideo"}
        </button>
        <button
          onClick={handleDownload}
          className="px-5 py-3 rounded-xl border border-gray-700 text-gray-300 hover:text-white hover:border-gray-500 transition-all text-sm font-semibold"
        >
          Download .txt
        </button>
      </div>

      {/* Scene list */}
      <div className="flex flex-col gap-3">
        {script.scenes.map((scene, i) => {
          const color = TYPE_COLOR[scene.type];
          const isOpen = expandedScene === i;
          return (
            <div
              key={scene.id}
              className="rounded-xl border border-white/8 bg-white/4 overflow-hidden"
              style={{ borderLeft: `3px solid ${color}` }}
            >
              {/* Scene header — always visible */}
              <button
                className="w-full text-left px-4 py-3 flex items-start gap-3 hover:bg-white/4 transition-all"
                onClick={() => setExpandedScene(isOpen ? null : i)}
              >
                <span
                  className="text-[10px] font-bold tracking-widest mt-0.5 shrink-0 rounded-full px-2 py-0.5"
                  style={{ background: `${color}22`, color }}
                >
                  {TYPE_LABEL[scene.type].toUpperCase()}
                </span>
                <div className="flex-1 min-w-0">
                  <p className="text-white font-semibold text-sm leading-snug truncate">{scene.headline}</p>
                  {!isOpen && (
                    <p className="text-gray-500 text-xs mt-0.5 line-clamp-1">{scene.narration}</p>
                  )}
                </div>
                <span className="text-gray-600 text-xs shrink-0 mt-0.5">{formatTime(scene.duration_seconds)}</span>
                <span className="text-gray-600 text-xs shrink-0 mt-0.5">{isOpen ? "▲" : "▼"}</span>
              </button>

              {/* Expanded content */}
              {isOpen && (
                <div className="px-4 pb-4 flex flex-col gap-3 border-t border-white/6 pt-3">
                  {/* Narration */}
                  <div>
                    <p className="text-xs font-semibold text-gray-500 uppercase tracking-widest mb-1.5">Narration</p>
                    <p className="text-gray-200 text-sm leading-relaxed">{scene.narration}</p>
                  </div>

                  {/* Visual prompt */}
                  {scene.image_prompt && (
                    <div className="rounded-lg bg-white/5 border border-white/8 px-3 py-2.5">
                      <p className="text-xs font-semibold mb-1" style={{ color }}>Visual prompt for InVideo</p>
                      <p className="text-gray-400 text-xs leading-relaxed italic">{scene.image_prompt}</p>
                    </div>
                  )}

                  {/* Key terms */}
                  {scene.key_terms && scene.key_terms.length > 0 && (
                    <div className="flex flex-wrap gap-1.5">
                      {scene.key_terms.map(t => (
                        <span
                          key={t}
                          className="text-xs px-2 py-0.5 rounded-full font-medium"
                          style={{ background: `${color}18`, color, border: `1px solid ${color}44` }}
                        >
                          {t}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
